name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      substrate:
        image: parity/substrate:latest
        ports:
          - 9944:9944

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Build WASM miner
        working-directory: substrate-node
        run: wasm-pack build --target web --features gpu

      - name: Build Substrate node
        working-directory: substrate-node/node
        run: cargo build --release

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install JS dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Run tests
        run: npm test
